---
- name: Optimize mysql myisam
  lineinfile: dest="{{ configurations.mysql.conf | default('/etc/my.cnf') }}" regexp="^{{ item.name }}" line="{{ item.name }} = {{ item.value }}"
  with_items: 
  - { name: "key_buffer_size:", value: "64M" }
  - { name: "sort_buffer_size", value: "32M" }
  - { name: "query_cache_limit", value: "2M" }
  - { name: "query_cache_size", value: "128M" }
  - { name: "query_cache_type", value: "1" }
  - { name: "max_heap_table_size", value: "128M" }
  - { name: "tmp_table_size", value: "128M" }
  - { name: "tmpdir", value: "/dev/shm" }                   
- name: Optimize mysql cache on server with ram higher 32GB
  lineinfile: dest="{{ configurations.mysql.conf | default('/etc/my.cnf') }}" regexp="^{{ item.name }}" line="{{ item.name }} = {{ item.value }}"
  with_items:
  - { name: "table_open_cache", value: "4096" }#in case of 32GB and higher set upto 4096-8192
  - { name: "thread_cache_size", value: "32" } #in case of 32GB and higher set upto 32
  when: ansible_memtotal_mb > 32*1024
- name: Optimize mysql cache on server with ram lower 32GB
  lineinfile: dest="{{ configurations.mysql.conf | default('/etc/my.cnf') }}" regexp="^{{ item.name }}" line="{{ item.name }} = {{ item.value }}"
  with_items:
  - { name: "table_open_cache", value: "2048" }#in case of 32GB and higher set upto 4096-8192
  - { name: "thread_cache_size", value: "16" } #in case of 32GB and higher set upto 32
  when: ansible_memtotal_mb < 32*1024

 
